openapi: 3.0.0
info:
  version: 1.0.0
  title: WantIt API documents.
  description: Server side code for WantIt.
  termsOfService: https://tkugimot.jp/terms
  contact:
    name: Toshimitsu Kugimoto
    url: url
    email: toshimitsu_kugimoto@yahoo.co.jp
  license:
    name: Toshimitsu Kugimoto
    url: https://tkugimot.jp
servers:
  - url: https://tkugimot.jp
    description: Production Server
paths:
  '/user':
    get:
      tags:
        - users
      description: Fetch User Info
      parameters:
        - name: id
          in: path
          description: user id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/User'
                example:
                  id: 1
                  uid: ABCDEFGHIJKLMNOP
                  dispname: Toshi
                  created_at: 2019/05/05
  '/user/posts':
    get:
      tags:
        - users
      description: Fetch Posts by User id
      parameters:
        - name: user_id
          in: path
          description: user id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
                example:
                  - id: 1
                    sentence: I want the App that you can post and share what kind of App you want.
                    img_url: img.jp
                    liked_count: 11
                    tags: [WebApp, iOSApp, AndroidApp]
                    created_at: 2019/05/05
                    updated_at: 2019/05/05
                    uid: ABCDEFHIJKLMNOP
                  - id: 2
                    sentence: Ups!
                    img_url: img2.jp
                    liked_count: 5
                    tags: [WebApp, iOSApp, AndroidApp]
                    created_at: 2019/05/05
                    updated_at: 2019/05/05
                    uid: ABCDEFHIJKLMNOP

  '/user/likes':
    get:
      tags:
        - users
      description: Fetch User Info
      parameters:
        - name: user_id
          in: path
          description: user id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Like'
                example:
                  - id: 1
                    user_id: ABCDEFGHIJKLMNOP
                    post_id: 15
                  - id: 5
                    user_id: ABCDEFGHIJKLMNOP
                    post_id: 17

  '/posts':
    get:
      tags:
        - posts
      description: Fetch All Posts by 10
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Post'
                example:
                  - id: 1
                    sentence: I want the App that you can post and share what kind of App you want.
                    img_url: img.jp
                    liked_count: 11
                    tags: [WebApp, iOSApp, AndroidApp]
                    created_at: 2019/05/05
                    updated_at: 2019/05/05
                    uid: ABCDEFHIJKLMNOP
                  - id: 2
                    sentence: AIUEO
                    img_url: img3.jp
                    liked_count: 3
                    tags: [WebApp, iOSApp, AndroidApp]
                    created_at: 2019/05/05
                    updated_at: 2019/05/05
                    uid: KAKIKIKEKOATAA

  '/post':
    get:
      tags:
        - posts
      description: Fetch post
      parameters:
        - name: post_id
          in: path
          description: user id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Post'
                example:
                  id: 1
                  sentence: I want the App that you can post and share what kind of App you want.
                  img_url: img.jp
                  liked_count: 11
                  tags: [WebApp, iOSApp, AndroidApp]
                  created_at: 2019/05/05
                  updated_at: 2019/05/05
                  uid: ABCDEFHIJKLMNOP

  '/post/likes':
    get:
      tags:
        - tags
      description: Fetch Likes by post_id
      parameters:
        - name: post_id
          in: path
          description: post id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Like'
                example:
                  - id: 1
                    user_id: ABCDEFGHIJKLMNOP
                    post_id: 3
                  - id: 5
                    user_id: AUDAVAEAFAEAFAFE
                    post_id: 3

tags:
  - name: users
    description: Fetch Users
  - name: posts
    description: Fetch Posts

components:
  schemas:
    User:
      type: object
      required:
        - id
        - uid
        - dispname
        - created_at
      properties:
        id:
          type: number
        uid:
          type: string
        dispname:
          type: string
        created_at:
          type: string
    Post:
      type: object
      required:
        - id
        - sentence
        - img_url
        - liked_count
        - tags
        - created_at
        - updated_at
        - uid
      properties:
        id:
          type: number
        sentence:
          type: string
        img_url:
          type: string
        liked_count:
          type: number
        tags:
          type: array
          items:
            type: string
        uid:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
    Like:
      type: object
      required:
        - id
        - uid
        - post_id
        - created_at
        - updated_at
      properties:
        id:
          type: number
        user_id:
          type: number
        post_id:
          type: number
        created_at:
          type: string
        updated_at:
          type: string
